defaultPortal: AeroRev
portals:
  - name: AeroRev
    portalId: 45587544
    authType: personalaccesstoken
    personalAccessKey: CiRuYTEtZDgyYi0zNjVkLTQyM2ItYjM3Mi0wNGI3NTcxNTkxOTMQ2LjeFRii6OwWKhkABeaRgrHgnnxcLMDbgPNlKYNCeyUAqqONSgNuYTE
